version: '3.7'

services:
  map:
    image: ghcr.io/otischung/pros_ai_image:latest
    env_file:
      - .env
    # environment:
    #   - ROS_DOMAIN_ID
    volumes:
      - ./demo/map/map01:/map
    networks:
      - my_bridge_network
    command: "ros2 run nav2_map_server map_saver_cli -f /map/map01"

networks:
  my_bridge_network:
    driver: bridge
