version: '3.7'

services:
  camera:
    image: public.ecr.aws/paia-tech/pros-camera:20231122
    env_file:
      - .env
    # environment:
    #   - ROS_DOMAIN_ID
    # devices:
    #   - "/dev/video0:/dev/video0"
    #   - "/dev/video1:/dev/video1"
    privileged: true
    networks:
      - my_bridge_network
    command: "ros2 launch astra_camera astro_pro_plus.launch.xml"

  rosbridge:
    image: public.ecr.aws/paia-tech/pros-camera:20231122
    env_file:
      - .env
    environment:
      - ROS_DOMAIN_ID

    # set bridge to host
    # network_mode: host
    # or export a port
    networks:
      - my_bridge_network
    ports:
      - 9090:9090
    command: " ros2 launch rosbridge_server rosbridge_websocket_launch.xml"

networks:
  my_bridge_network:
    driver: bridge
