version: '3.7'

services:
  rplidar:
    image: public.ecr.aws/paia-tech/pros-utils:20231121
    env_file:
      - .env
    environment:
      - ROS_DOMAIN_ID
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/video1:/dev/ttyUSB0"
    volumes:
      - ./demo:/workspace/demo:ro
    networks:
      - my_bridge_network
    command: "ros2 launch ./demo/rplidar.xml"
  
  slam:
    image: public.ecr.aws/paia-tech/pros-utils:20231121
    env_file:
      - .env
    environment:
      - ROS_DOMAIN_ID
    volumes:
      - ./demo:/workspace/demo:ro
    networks:
      - my_bridge_network
    command: "ros2 launch ./demo/slam.xml"
  
  localization:
    image: public.ecr.aws/paia-tech/pros-utils:20231121
    env_file:
      - .env
    environment:
      - ROS_DOMAIN_ID
    volumes:
      - ./demo:/workspace/demo:ro
    networks:
      - my_bridge_network
    command: "ros2 launch ./demo/localization.xml"
  
  camera:
    image: public.ecr.aws/paia-tech/pros-camera:20231122
    env_file:
      - .env
    environment:
      - ROS_DOMAIN_ID

    networks:
      - my_bridge_network
    command: "ros2 launch astra_camera astro_pro_plus.launch.xml"

networks:
  my_bridge_network:
    driver: bridge
