services:
  navigation:
    image: registry.screamtrumpet.csie.ncku.edu.tw/pros_images/pros_jetson_driver_image:latest
    env_file:
      - .env
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    environment:
      - SIZE=${SIZE}
      - SQUARE=${SQUARE}
      - IMAGE_TOPIC=${IMAGE_TOPIC}
      - CAMERA_NAME=${CAMERA_NAME}
    volumes:
      - ./demo:/workspace/demo:ro
    networks:
      - my_bridge_network
    command: >
      bash -c "ros2 launch /workspace/demo/camera_calibration.xml
               --size ${SIZE} --square ${SQUARE} 
               --ros-args -r image:=${IMAGE_TOPIC} -p camera:=${CAMERA_NAME}"
networks:
  my_bridge_network:
    driver: bridge
