services:
  navigation:
    image: registry.screamtrumpet.csie.ncku.edu.tw/pros_images/pros_jetson_driver_image:latest
    env_file:
      - .env
    environment:
      - SIZE=${SIZE}
      - SQUARE=${SQUARE}
      - IMAGE_TOPIC=${IMAGE_TOPIC}
      - CAMERA_NAME=${CAMERA_NAME}
      - DISPLAY=$DISPLAY
    volumes:
      - ./demo:/workspace/demo:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - my_bridge_network
    command: >
      bash -c "ros2 launch /workspace/demo/camera_calibration.launch.py
               --size ${SIZE} --square ${SQUARE} 
               --ros-args -r image:=${IMAGE_TOPIC} -p camera:=${CAMERA_NAME}"

networks:
  my_bridge_network:
    driver: bridge
